title: Camilla Marabini
page-top-title: Camilla Marabini
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Camilla Marabini 2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/senli1073
license-link:
  text: License
  href: https://github.com/senli1073/senli1073.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: About me
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
